#!/Users/fyslalrashd/Documents/Codex/2026-09-05/virtual-work-environment-ai-agent-x20/.venv/bin/python3.13
# -*- coding: utf-8 -*-
import re
import sys
from cffi._cffi_gen_src import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
